/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, WebhookScheduledTrigger } from "@prisma/client";

export class WebhookScheduledTriggerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.WebhookScheduledTriggerCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.WebhookScheduledTriggerCountArgs>
  ): Promise<number> {
    return this.prisma.webhookScheduledTrigger.count(args);
  }

  async webhookScheduledTriggers<
    T extends Prisma.WebhookScheduledTriggerFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.WebhookScheduledTriggerFindManyArgs>
  ): Promise<WebhookScheduledTrigger[]> {
    return this.prisma.webhookScheduledTrigger.findMany(args);
  }
  async webhookScheduledTrigger<
    T extends Prisma.WebhookScheduledTriggerFindUniqueArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.WebhookScheduledTriggerFindUniqueArgs>
  ): Promise<WebhookScheduledTrigger | null> {
    return this.prisma.webhookScheduledTrigger.findUnique(args);
  }
  async createWebhookScheduledTrigger<
    T extends Prisma.WebhookScheduledTriggerCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.WebhookScheduledTriggerCreateArgs>
  ): Promise<WebhookScheduledTrigger> {
    return this.prisma.webhookScheduledTrigger.create<T>(args);
  }
  async updateWebhookScheduledTrigger<
    T extends Prisma.WebhookScheduledTriggerUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.WebhookScheduledTriggerUpdateArgs>
  ): Promise<WebhookScheduledTrigger> {
    return this.prisma.webhookScheduledTrigger.update<T>(args);
  }
  async deleteWebhookScheduledTrigger<
    T extends Prisma.WebhookScheduledTriggerDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.WebhookScheduledTriggerDeleteArgs>
  ): Promise<WebhookScheduledTrigger> {
    return this.prisma.webhookScheduledTrigger.delete(args);
  }
}
