import { AccessCodeListRelationFilter } from "../accessCode/AccessCodeListRelationFilter";
import { ApiKeyListRelationFilter } from "../apiKey/ApiKeyListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { TeamListRelationFilter } from "./TeamListRelationFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { CredentialListRelationFilter } from "../credential/CredentialListRelationFilter";
import { EventTypeListRelationFilter } from "../eventType/EventTypeListRelationFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { IntFilter } from "../../util/IntFilter";
import { InstantMeetingTokenListRelationFilter } from "../instantMeetingToken/InstantMeetingTokenListRelationFilter";
import { VerificationTokenListRelationFilter } from "../verificationToken/VerificationTokenListRelationFilter";
import { MembershipListRelationFilter } from "../membership/MembershipListRelationFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { StringFilter } from "../../util/StringFilter";
import { ProfileListRelationFilter } from "../profile/ProfileListRelationFilter";
import { UserListRelationFilter } from "../user/UserListRelationFilter";
import { TeamWhereUniqueInput } from "./TeamWhereUniqueInput";
import { AppRoutingFormsFormListRelationFilter } from "../appRoutingFormsForm/AppRoutingFormsFormListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { VerifiedNumberListRelationFilter } from "../verifiedNumber/VerifiedNumberListRelationFilter";
import { WebhookListRelationFilter } from "../webhook/WebhookListRelationFilter";
import { WorkflowListRelationFilter } from "../workflow/WorkflowListRelationFilter";

export type TeamWhereInput = {
  accessCodes?: AccessCodeListRelationFilter;
  apiKeys?: ApiKeyListRelationFilter;
  appIconLogo?: StringNullableFilter;
  appLogo?: StringNullableFilter;
  bio?: StringNullableFilter;
  brandColor?: StringNullableFilter;
  calVideoLogo?: StringNullableFilter;
  children?: TeamListRelationFilter;
  createdAt?: DateTimeFilter;
  credentials?: CredentialListRelationFilter;
  darkBrandColor?: StringNullableFilter;
  eventTypes?: EventTypeListRelationFilter;
  hideBookATeamMember?: BooleanFilter;
  hideBranding?: BooleanFilter;
  id?: IntFilter;
  instantMeetingTokens?: InstantMeetingTokenListRelationFilter;
  inviteTokens?: VerificationTokenListRelationFilter;
  isPrivate?: BooleanFilter;
  logo?: StringNullableFilter;
  logoUrl?: StringNullableFilter;
  members?: MembershipListRelationFilter;
  metadata?: JsonFilter;
  name?: StringFilter;
  orgProfiles?: ProfileListRelationFilter;
  orgUsers?: UserListRelationFilter;
  parent?: TeamWhereUniqueInput;
  pendingPayment?: BooleanFilter;
  routingForms?: AppRoutingFormsFormListRelationFilter;
  slug?: StringNullableFilter;
  theme?: StringNullableFilter;
  timeFormat?: IntNullableFilter;
  timeZone?: StringFilter;
  verifiedNumbers?: VerifiedNumberListRelationFilter;
  webhooks?: WebhookListRelationFilter;
  weekStart?: StringFilter;
  workflows?: WorkflowListRelationFilter;
};
