import { AccessCode } from "../accessCode/AccessCode";
import { ApiKey } from "../apiKey/ApiKey";
import { Credential } from "../credential/Credential";
import { EventType } from "../eventType/EventType";
import { InstantMeetingToken } from "../instantMeetingToken/InstantMeetingToken";
import { VerificationToken } from "../verificationToken/VerificationToken";
import { Membership } from "../membership/Membership";
import { JsonValue } from "type-fest";
import { Profile } from "../profile/Profile";
import { User } from "../user/User";
import { AppRoutingFormsForm } from "../appRoutingFormsForm/AppRoutingFormsForm";
import { VerifiedNumber } from "../verifiedNumber/VerifiedNumber";
import { Webhook } from "../webhook/Webhook";
import { Workflow } from "../workflow/Workflow";

export type Team = {
  accessCodes?: Array<AccessCode>;
  apiKeys?: Array<ApiKey>;
  appIconLogo: string | null;
  appLogo: string | null;
  bio: string | null;
  brandColor: string | null;
  calVideoLogo: string | null;
  children?: Array<Team>;
  createdAt: Date;
  credentials?: Array<Credential>;
  darkBrandColor: string | null;
  eventTypes?: Array<EventType>;
  hideBookATeamMember: boolean;
  hideBranding: boolean;
  id: number;
  instantMeetingTokens?: Array<InstantMeetingToken>;
  inviteTokens?: Array<VerificationToken>;
  isPrivate: boolean;
  logo: string | null;
  logoUrl: string | null;
  members?: Array<Membership>;
  metadata: JsonValue;
  name: string;
  orgProfiles?: Array<Profile>;
  orgUsers?: Array<User>;
  parent?: Team | null;
  pendingPayment: boolean;
  routingForms?: Array<AppRoutingFormsForm>;
  slug: string | null;
  theme: string | null;
  timeFormat: number | null;
  timeZone: string;
  verifiedNumbers?: Array<VerifiedNumber>;
  webhooks?: Array<Webhook>;
  weekStart: string;
  workflows?: Array<Workflow>;
};
