/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { User1WhereUniqueInput } from "../../user1/base/User1WhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";

@InputType()
class User1CreateNestedManyWithoutSkillsInput {
  @Field(() => [User1WhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [User1WhereUniqueInput],
  })
  connect?: Array<User1WhereUniqueInput>;
}

export { User1CreateNestedManyWithoutSkillsInput as User1CreateNestedManyWithoutSkillsInput };
