/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AppModelWhereUniqueInput } from "../../appModel/base/AppModelWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsInt,
  IsBoolean,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { CalendarCacheCreateNestedManyWithoutCredentialsInput } from "./CalendarCacheCreateNestedManyWithoutCredentialsInput";
import { DestinationCalendarCreateNestedManyWithoutCredentialsInput } from "./DestinationCalendarCreateNestedManyWithoutCredentialsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SelectedCalendarCreateNestedManyWithoutCredentialsInput } from "./SelectedCalendarCreateNestedManyWithoutCredentialsInput";
import { TeamWhereUniqueInput } from "../../team/base/TeamWhereUniqueInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class CredentialCreateInput {
  @ApiProperty({
    required: false,
    type: () => AppModelWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AppModelWhereUniqueInput)
  @IsOptional()
  @Field(() => AppModelWhereUniqueInput, {
    nullable: true,
  })
  appField?: AppModelWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  billingCycleStart?: number | null;

  @ApiProperty({
    required: false,
    type: () => CalendarCacheCreateNestedManyWithoutCredentialsInput,
  })
  @ValidateNested()
  @Type(() => CalendarCacheCreateNestedManyWithoutCredentialsInput)
  @IsOptional()
  @Field(() => CalendarCacheCreateNestedManyWithoutCredentialsInput, {
    nullable: true,
  })
  calendarCache?: CalendarCacheCreateNestedManyWithoutCredentialsInput;

  @ApiProperty({
    required: false,
    type: () => DestinationCalendarCreateNestedManyWithoutCredentialsInput,
  })
  @ValidateNested()
  @Type(() => DestinationCalendarCreateNestedManyWithoutCredentialsInput)
  @IsOptional()
  @Field(() => DestinationCalendarCreateNestedManyWithoutCredentialsInput, {
    nullable: true,
  })
  destinationCalendars?: DestinationCalendarCreateNestedManyWithoutCredentialsInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  invalid?: boolean | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  key!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  paymentStatus?: string | null;

  @ApiProperty({
    required: false,
    type: () => SelectedCalendarCreateNestedManyWithoutCredentialsInput,
  })
  @ValidateNested()
  @Type(() => SelectedCalendarCreateNestedManyWithoutCredentialsInput)
  @IsOptional()
  @Field(() => SelectedCalendarCreateNestedManyWithoutCredentialsInput, {
    nullable: true,
  })
  selectedCalendars?: SelectedCalendarCreateNestedManyWithoutCredentialsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subscriptionId?: string | null;

  @ApiProperty({
    required: false,
    type: () => TeamWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TeamWhereUniqueInput)
  @IsOptional()
  @Field(() => TeamWhereUniqueInput, {
    nullable: true,
  })
  team?: TeamWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  typeField!: string;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { CredentialCreateInput as CredentialCreateInput };
