import { JsonFilter } from "../../util/JsonFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { IntFilter } from "../../util/IntFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";

export type UserWhereInput = {
  accessCodes?: JsonFilter;
  accounts?: JsonFilter;
  allowDynamicBooking?: BooleanNullableFilter;
  allowSEOIndexing?: BooleanNullableFilter;
  apiKeys?: JsonFilter;
  appTheme?: StringNullableFilter;
  availability?: JsonFilter;
  avatar?: StringNullableFilter;
  avatarUrl?: StringNullableFilter;
  away?: BooleanFilter;
  backupCodes?: StringNullableFilter;
  bio?: StringNullableFilter;
  bookingRedirects?: JsonFilter;
  bookingRedirectsTo?: JsonFilter;
  bookings?: JsonFilter;
  brandColor?: StringNullableFilter;
  bufferTime?: IntFilter;
  completedOnboarding?: BooleanFilter;
  createdDate?: DateTimeFilter;
  credentials?: JsonFilter;
  darkBrandColor?: StringNullableFilter;
  defaultScheduleId?: IntNullableFilter;
  destinationCalendarId?: IntNullableFilter;
  disableImpersonation?: BooleanFilter;
  email?: StringFilter;
  emailVerified?: DateTimeNullableFilter;
  endTime?: IntFilter;
  feedback?: JsonFilter;
  hideBranding?: BooleanFilter;
  hosts?: JsonFilter;
  id?: IntFilter;
  identityProvider?: "CAL" | "GOOGLE" | "SAML";
  identityProviderId?: StringNullableFilter;
  impersonatedBy?: JsonFilter;
  impersonatedUsers?: JsonFilter;
  invitedTo?: IntNullableFilter;
  locale?: StringNullableFilter;
  locked?: BooleanFilter;
  metadata?: JsonFilter;
  movedToProfileId?: IntNullableFilter;
  name?: StringNullableFilter;
  organizationId?: IntNullableFilter;
  ownedEventTypes?: JsonFilter;
  passwordId?: IntNullableFilter;
  profiles?: JsonFilter;
  receiveMonthlyDigestEmail?: BooleanNullableFilter;
  role?: "USER" | "ADMIN";
  routingForms?: JsonFilter;
  schedules?: JsonFilter;
  selectedCalendars?: JsonFilter;
  sessions?: JsonFilter;
  startTime?: IntFilter;
  teams?: JsonFilter;
  theme?: StringNullableFilter;
  timeFormat?: IntNullableFilter;
  timeZone?: StringFilter;
  trialEndsAt?: DateTimeNullableFilter;
  twoFactorEnabled?: BooleanFilter;
  twoFactorSecret?: StringNullableFilter;
  username?: StringNullableFilter;
  verified?: BooleanNullableFilter;
  verifiedNumbers?: JsonFilter;
  webhooks?: JsonFilter;
  weekStart?: StringFilter;
  workflows?: JsonFilter;
};
