import { InputJsonValue } from "../../types";

export type UserCreateInput = {
  accessCodes?: InputJsonValue;
  accounts?: InputJsonValue;
  allowDynamicBooking?: boolean | null;
  allowSEOIndexing?: boolean | null;
  apiKeys?: InputJsonValue;
  appTheme?: string | null;
  availability?: InputJsonValue;
  avatar?: string | null;
  avatarUrl?: string | null;
  away: boolean;
  backupCodes?: string | null;
  bio?: string | null;
  bookingRedirects?: InputJsonValue;
  bookingRedirectsTo?: InputJsonValue;
  bookings?: InputJsonValue;
  brandColor?: string | null;
  bufferTime: number;
  completedOnboarding: boolean;
  credentials?: InputJsonValue;
  darkBrandColor?: string | null;
  defaultScheduleId?: number | null;
  destinationCalendarId?: number | null;
  disableImpersonation: boolean;
  email: string;
  emailVerified?: Date | null;
  endTime: number;
  feedback?: InputJsonValue;
  hideBranding: boolean;
  hosts?: InputJsonValue;
  identityProvider: "CAL" | "GOOGLE" | "SAML";
  identityProviderId?: string | null;
  impersonatedBy?: InputJsonValue;
  impersonatedUsers?: InputJsonValue;
  invitedTo?: number | null;
  locale?: string | null;
  locked: boolean;
  metadata?: InputJsonValue;
  movedToProfileId?: number | null;
  name?: string | null;
  organizationId?: number | null;
  ownedEventTypes?: InputJsonValue;
  passwordId?: number | null;
  profiles?: InputJsonValue;
  receiveMonthlyDigestEmail?: boolean | null;
  role: "USER" | "ADMIN";
  routingForms?: InputJsonValue;
  schedules?: InputJsonValue;
  selectedCalendars?: InputJsonValue;
  sessions?: InputJsonValue;
  startTime: number;
  teams?: InputJsonValue;
  theme?: string | null;
  timeFormat?: number | null;
  timeZone: string;
  trialEndsAt?: Date | null;
  twoFactorEnabled: boolean;
  twoFactorSecret?: string | null;
  username?: string | null;
  verified?: boolean | null;
  verifiedNumbers?: InputJsonValue;
  webhooks?: InputJsonValue;
  weekStart: string;
  workflows?: InputJsonValue;
};
