import { JsonValue } from "type-fest";

export type User = {
  accessCodes: JsonValue;
  accounts: JsonValue;
  allowDynamicBooking: boolean | null;
  allowSEOIndexing: boolean | null;
  apiKeys: JsonValue;
  appTheme: string | null;
  availability: JsonValue;
  avatar: string | null;
  avatarUrl: string | null;
  away: boolean;
  backupCodes: string | null;
  bio: string | null;
  bookingRedirects: JsonValue;
  bookingRedirectsTo: JsonValue;
  bookings: JsonValue;
  brandColor: string | null;
  bufferTime: number;
  completedOnboarding: boolean;
  createdDate: Date;
  credentials: JsonValue;
  darkBrandColor: string | null;
  defaultScheduleId: number | null;
  destinationCalendarId: number | null;
  disableImpersonation: boolean;
  email: string;
  emailVerified: Date | null;
  endTime: number;
  feedback: JsonValue;
  hideBranding: boolean;
  hosts: JsonValue;
  id: number;
  identityProvider?: "CAL" | "GOOGLE" | "SAML";
  identityProviderId: string | null;
  impersonatedBy: JsonValue;
  impersonatedUsers: JsonValue;
  invitedTo: number | null;
  locale: string | null;
  locked: boolean;
  metadata: JsonValue;
  movedToProfileId: number | null;
  name: string | null;
  organizationId: number | null;
  ownedEventTypes: JsonValue;
  passwordId: number | null;
  profiles: JsonValue;
  receiveMonthlyDigestEmail: boolean | null;
  role?: "USER" | "ADMIN";
  routingForms: JsonValue;
  schedules: JsonValue;
  selectedCalendars: JsonValue;
  sessions: JsonValue;
  startTime: number;
  teams: JsonValue;
  theme: string | null;
  timeFormat: number | null;
  timeZone: string;
  trialEndsAt: Date | null;
  twoFactorEnabled: boolean;
  twoFactorSecret: string | null;
  username: string | null;
  verified: boolean | null;
  verifiedNumbers: JsonValue;
  webhooks: JsonValue;
  weekStart: string;
  workflows: JsonValue;
};
