/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Msgbroker } from "./Msgbroker";
import { MsgbrokerCountArgs } from "./MsgbrokerCountArgs";
import { MsgbrokerFindManyArgs } from "./MsgbrokerFindManyArgs";
import { MsgbrokerFindUniqueArgs } from "./MsgbrokerFindUniqueArgs";
import { DeleteMsgbrokerArgs } from "./DeleteMsgbrokerArgs";
import { MsgbrokerService } from "../msgbroker.service";
@graphql.Resolver(() => Msgbroker)
export class MsgbrokerResolverBase {
  constructor(protected readonly service: MsgbrokerService) {}

  async _msgbrokersMeta(
    @graphql.Args() args: MsgbrokerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Msgbroker])
  async msgbrokers(
    @graphql.Args() args: MsgbrokerFindManyArgs
  ): Promise<Msgbroker[]> {
    return this.service.msgbrokers(args);
  }

  @graphql.Query(() => Msgbroker, { nullable: true })
  async msgbroker(
    @graphql.Args() args: MsgbrokerFindUniqueArgs
  ): Promise<Msgbroker | null> {
    const result = await this.service.msgbroker(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Msgbroker)
  async deleteMsgbroker(
    @graphql.Args() args: DeleteMsgbrokerArgs
  ): Promise<Msgbroker | null> {
    try {
      return await this.service.deleteMsgbroker(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
