import { Attendee } from "../attendee/Attendee";
import { JsonValue } from "type-fest";
import { DestinationCalendar } from "../destinationCalendar/DestinationCalendar";
import { EventType } from "../eventType/EventType";
import { InstantMeetingToken } from "../instantMeetingToken/InstantMeetingToken";
import { Payment } from "../payment/Payment";
import { BookingReference } from "../bookingReference/BookingReference";
import { BookingSeat } from "../bookingSeat/BookingSeat";
import { User } from "../user/User";
import { WorkflowReminder } from "../workflowReminder/WorkflowReminder";

export type Booking = {
  attendees?: Array<Attendee>;
  cancellationReason: string | null;
  createdAt: Date;
  customInputs: JsonValue;
  description: string | null;
  destinationCalendar?: DestinationCalendar | null;
  dynamicEventSlugRef: string | null;
  dynamicGroupSlugRef: string | null;
  endTime: Date;
  eventType?: EventType | null;
  fromReschedule: string | null;
  iCalSequence: number;
  iCalUID: string | null;
  id: number;
  instantMeetingToken?: InstantMeetingToken | null;
  isRecorded: boolean;
  location: string | null;
  metadata: JsonValue;
  paid: boolean;
  payment?: Array<Payment>;
  recurringEventId: string | null;
  references?: Array<BookingReference>;
  rejectionReason: string | null;
  rescheduled: boolean | null;
  responses: JsonValue;
  scheduledJobs: string;
  seatsReferences?: Array<BookingSeat>;
  smsReminderNumber: string | null;
  startTime: Date;
  status?: "CANCELLED" | "ACCEPTED" | "REJECTED" | "PENDING" | "AWAITING_HOST";
  title: string;
  uid: string;
  updatedAt: Date | null;
  user?: User | null;
  userPrimaryEmail: string | null;
  workflowReminders?: Array<WorkflowReminder>;
};
