import { AttendeeListRelationFilter } from "../attendee/AttendeeListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { EventTypeWhereUniqueInput } from "../eventType/EventTypeWhereUniqueInput";
import { IntFilter } from "../../util/IntFilter";
import { InstantMeetingTokenWhereUniqueInput } from "../instantMeetingToken/InstantMeetingTokenWhereUniqueInput";
import { BooleanFilter } from "../../util/BooleanFilter";
import { PaymentListRelationFilter } from "../payment/PaymentListRelationFilter";
import { BookingReferenceListRelationFilter } from "../bookingReference/BookingReferenceListRelationFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { BookingSeatListRelationFilter } from "../bookingSeat/BookingSeatListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { WorkflowReminderListRelationFilter } from "../workflowReminder/WorkflowReminderListRelationFilter";

export type BookingWhereInput = {
  attendees?: AttendeeListRelationFilter;
  cancellationReason?: StringNullableFilter;
  createdAt?: DateTimeFilter;
  customInputs?: JsonFilter;
  description?: StringNullableFilter;
  destinationCalendar?: DestinationCalendarWhereUniqueInput;
  dynamicEventSlugRef?: StringNullableFilter;
  dynamicGroupSlugRef?: StringNullableFilter;
  endTime?: DateTimeFilter;
  eventType?: EventTypeWhereUniqueInput;
  fromReschedule?: StringNullableFilter;
  iCalSequence?: IntFilter;
  iCalUID?: StringNullableFilter;
  id?: IntFilter;
  instantMeetingToken?: InstantMeetingTokenWhereUniqueInput;
  isRecorded?: BooleanFilter;
  location?: StringNullableFilter;
  metadata?: JsonFilter;
  paid?: BooleanFilter;
  payment?: PaymentListRelationFilter;
  recurringEventId?: StringNullableFilter;
  references?: BookingReferenceListRelationFilter;
  rejectionReason?: StringNullableFilter;
  rescheduled?: BooleanNullableFilter;
  responses?: JsonFilter;
  scheduledJobs?: StringFilter;
  seatsReferences?: BookingSeatListRelationFilter;
  smsReminderNumber?: StringNullableFilter;
  startTime?: DateTimeFilter;
  status?: "CANCELLED" | "ACCEPTED" | "REJECTED" | "PENDING" | "AWAITING_HOST";
  title?: StringFilter;
  uid?: StringFilter;
  updatedAt?: DateTimeNullableFilter;
  user?: UserWhereUniqueInput;
  userPrimaryEmail?: StringNullableFilter;
  workflowReminders?: WorkflowReminderListRelationFilter;
};
