import { AttendeeCreateNestedManyWithoutBookingsInput } from "./AttendeeCreateNestedManyWithoutBookingsInput";
import { InputJsonValue } from "../../types";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { EventTypeWhereUniqueInput } from "../eventType/EventTypeWhereUniqueInput";
import { InstantMeetingTokenWhereUniqueInput } from "../instantMeetingToken/InstantMeetingTokenWhereUniqueInput";
import { PaymentCreateNestedManyWithoutBookingsInput } from "./PaymentCreateNestedManyWithoutBookingsInput";
import { BookingReferenceCreateNestedManyWithoutBookingsInput } from "./BookingReferenceCreateNestedManyWithoutBookingsInput";
import { BookingSeatCreateNestedManyWithoutBookingsInput } from "./BookingSeatCreateNestedManyWithoutBookingsInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { WorkflowReminderCreateNestedManyWithoutBookingsInput } from "./WorkflowReminderCreateNestedManyWithoutBookingsInput";

export type BookingCreateInput = {
  attendees?: AttendeeCreateNestedManyWithoutBookingsInput;
  cancellationReason?: string | null;
  customInputs?: InputJsonValue;
  description?: string | null;
  destinationCalendar?: DestinationCalendarWhereUniqueInput | null;
  dynamicEventSlugRef?: string | null;
  dynamicGroupSlugRef?: string | null;
  endTime: Date;
  eventType?: EventTypeWhereUniqueInput | null;
  fromReschedule?: string | null;
  iCalSequence: number;
  iCalUID?: string | null;
  instantMeetingToken?: InstantMeetingTokenWhereUniqueInput | null;
  isRecorded: boolean;
  location?: string | null;
  metadata?: InputJsonValue;
  paid: boolean;
  payment?: PaymentCreateNestedManyWithoutBookingsInput;
  recurringEventId?: string | null;
  references?: BookingReferenceCreateNestedManyWithoutBookingsInput;
  rejectionReason?: string | null;
  rescheduled?: boolean | null;
  responses?: InputJsonValue;
  scheduledJobs: string;
  seatsReferences?: BookingSeatCreateNestedManyWithoutBookingsInput;
  smsReminderNumber?: string | null;
  startTime: Date;
  status: "CANCELLED" | "ACCEPTED" | "REJECTED" | "PENDING" | "AWAITING_HOST";
  title: string;
  uid: string;
  updatedAt?: Date | null;
  user?: UserWhereUniqueInput | null;
  userPrimaryEmail?: string | null;
  workflowReminders?: WorkflowReminderCreateNestedManyWithoutBookingsInput;
};
