import { AttendeeUpdateManyWithoutBookingsInput } from "./AttendeeUpdateManyWithoutBookingsInput";
import { InputJsonValue } from "../../types";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { EventTypeWhereUniqueInput } from "../eventType/EventTypeWhereUniqueInput";
import { InstantMeetingTokenWhereUniqueInput } from "../instantMeetingToken/InstantMeetingTokenWhereUniqueInput";
import { PaymentUpdateManyWithoutBookingsInput } from "./PaymentUpdateManyWithoutBookingsInput";
import { BookingReferenceUpdateManyWithoutBookingsInput } from "./BookingReferenceUpdateManyWithoutBookingsInput";
import { BookingSeatUpdateManyWithoutBookingsInput } from "./BookingSeatUpdateManyWithoutBookingsInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { WorkflowReminderUpdateManyWithoutBookingsInput } from "./WorkflowReminderUpdateManyWithoutBookingsInput";

export type BookingUpdateInput = {
  attendees?: AttendeeUpdateManyWithoutBookingsInput;
  cancellationReason?: string | null;
  customInputs?: InputJsonValue;
  description?: string | null;
  destinationCalendar?: DestinationCalendarWhereUniqueInput | null;
  dynamicEventSlugRef?: string | null;
  dynamicGroupSlugRef?: string | null;
  endTime?: Date;
  eventType?: EventTypeWhereUniqueInput | null;
  fromReschedule?: string | null;
  iCalSequence?: number;
  iCalUID?: string | null;
  instantMeetingToken?: InstantMeetingTokenWhereUniqueInput | null;
  isRecorded?: boolean;
  location?: string | null;
  metadata?: InputJsonValue;
  paid?: boolean;
  payment?: PaymentUpdateManyWithoutBookingsInput;
  recurringEventId?: string | null;
  references?: BookingReferenceUpdateManyWithoutBookingsInput;
  rejectionReason?: string | null;
  rescheduled?: boolean | null;
  responses?: InputJsonValue;
  scheduledJobs?: string;
  seatsReferences?: BookingSeatUpdateManyWithoutBookingsInput;
  smsReminderNumber?: string | null;
  startTime?: Date;
  status?: "CANCELLED" | "ACCEPTED" | "REJECTED" | "PENDING" | "AWAITING_HOST";
  title?: string;
  uid?: string;
  updatedAt?: Date | null;
  user?: UserWhereUniqueInput | null;
  userPrimaryEmail?: string | null;
  workflowReminders?: WorkflowReminderUpdateManyWithoutBookingsInput;
};
