import { SortOrder } from "../../util/SortOrder";

export type BookingOrderByInput = {
  cancellationReason?: SortOrder;
  createdAt?: SortOrder;
  customInputs?: SortOrder;
  description?: SortOrder;
  destinationCalendarId?: SortOrder;
  dynamicEventSlugRef?: SortOrder;
  dynamicGroupSlugRef?: SortOrder;
  endTime?: SortOrder;
  eventTypeId?: SortOrder;
  fromReschedule?: SortOrder;
  iCalSequence?: SortOrder;
  iCalUID?: SortOrder;
  id?: SortOrder;
  instantMeetingTokenId?: SortOrder;
  isRecorded?: SortOrder;
  location?: SortOrder;
  metadata?: SortOrder;
  paid?: SortOrder;
  recurringEventId?: SortOrder;
  rejectionReason?: SortOrder;
  rescheduled?: SortOrder;
  responses?: SortOrder;
  scheduledJobs?: SortOrder;
  smsReminderNumber?: SortOrder;
  startTime?: SortOrder;
  status?: SortOrder;
  title?: SortOrder;
  uid?: SortOrder;
  updatedAt?: SortOrder;
  userId?: SortOrder;
  userPrimaryEmail?: SortOrder;
};
