import { IntFilter } from "../../util/IntFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { AvailabilityListRelationFilter } from "../availability/AvailabilityListRelationFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { BookingListRelationFilter } from "../booking/BookingListRelationFilter";
import { EventTypeListRelationFilter } from "./EventTypeListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { EventTypeCustomInputListRelationFilter } from "../eventTypeCustomInput/EventTypeCustomInputListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { HashedLinkWhereUniqueInput } from "../hashedLink/HashedLinkWhereUniqueInput";
import { HostListRelationFilter } from "../host/HostListRelationFilter";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { EventTypeWhereUniqueInput } from "./EventTypeWhereUniqueInput";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { ProfileWhereUniqueInput } from "../profile/ProfileWhereUniqueInput";
import { ScheduleWhereUniqueInput } from "../schedule/ScheduleWhereUniqueInput";
import { TeamWhereUniqueInput } from "../team/TeamWhereUniqueInput";
import { WebhookListRelationFilter } from "../webhook/WebhookListRelationFilter";
import { WorkflowsOnEventTypeListRelationFilter } from "../workflowsOnEventType/WorkflowsOnEventTypeListRelationFilter";

export type EventTypeWhereInput = {
  afterEventBuffer?: IntFilter;
  assignAllTeamMembers?: BooleanFilter;
  availability?: AvailabilityListRelationFilter;
  beforeEventBuffer?: IntFilter;
  bookingFields?: JsonFilter;
  bookingLimits?: JsonFilter;
  bookings?: BookingListRelationFilter;
  children?: EventTypeListRelationFilter;
  currency?: StringFilter;
  customInputs?: EventTypeCustomInputListRelationFilter;
  description?: StringNullableFilter;
  destinationCalendar?: DestinationCalendarWhereUniqueInput;
  disableGuests?: BooleanFilter;
  durationLimits?: JsonFilter;
  eventName?: StringNullableFilter;
  hashedLink?: HashedLinkWhereUniqueInput;
  hidden?: BooleanFilter;
  hideCalendarNotes?: BooleanFilter;
  hosts?: HostListRelationFilter;
  id?: IntFilter;
  isInstantEvent?: BooleanFilter;
  length?: IntFilter;
  locations?: JsonFilter;
  lockTimeZoneToggleOnBookingPage?: BooleanFilter;
  metadata?: JsonFilter;
  minimumBookingNotice?: IntFilter;
  offsetStart?: IntFilter;
  onlyShowFirstAvailableSlot?: BooleanFilter;
  owner?: UserWhereUniqueInput;
  parent?: EventTypeWhereUniqueInput;
  periodCountCalendarDays?: BooleanNullableFilter;
  periodDays?: IntNullableFilter;
  periodEndDate?: DateTimeNullableFilter;
  periodStartDate?: DateTimeNullableFilter;
  periodType?: "UNLIMITED" | "ROLLING" | "RANGE";
  position?: IntFilter;
  price?: IntFilter;
  profile?: ProfileWhereUniqueInput;
  recurringEvent?: JsonFilter;
  requiresBookerEmailVerification?: BooleanFilter;
  requiresConfirmation?: BooleanFilter;
  schedule?: ScheduleWhereUniqueInput;
  schedulingType?: "ROUND_ROBIN" | "COLLECTIVE" | "MANAGED";
  seatsPerTimeSlot?: IntNullableFilter;
  seatsShowAttendees?: BooleanNullableFilter;
  seatsShowAvailabilityCount?: BooleanNullableFilter;
  slotInterval?: IntNullableFilter;
  slug?: StringFilter;
  successRedirectUrl?: StringNullableFilter;
  team?: TeamWhereUniqueInput;
  timeZone?: StringNullableFilter;
  title?: StringFilter;
  useEventTypeDestinationCalendarEmail?: BooleanFilter;
  webhooks?: WebhookListRelationFilter;
  workflows?: WorkflowsOnEventTypeListRelationFilter;
};
