import { Availability } from "../availability/Availability";
import { JsonValue } from "type-fest";
import { Booking } from "../booking/Booking";
import { EventTypeCustomInput } from "../eventTypeCustomInput/EventTypeCustomInput";
import { DestinationCalendar } from "../destinationCalendar/DestinationCalendar";
import { HashedLink } from "../hashedLink/HashedLink";
import { Host } from "../host/Host";
import { User } from "../user/User";
import { Profile } from "../profile/Profile";
import { Schedule } from "../schedule/Schedule";
import { Team } from "../team/Team";
import { Webhook } from "../webhook/Webhook";
import { WorkflowsOnEventType } from "../workflowsOnEventType/WorkflowsOnEventType";

export type EventType = {
  afterEventBuffer: number;
  assignAllTeamMembers: boolean;
  availability?: Array<Availability>;
  beforeEventBuffer: number;
  bookingFields: JsonValue;
  bookingLimits: JsonValue;
  bookings?: Array<Booking>;
  children?: Array<EventType>;
  currency: string;
  customInputs?: Array<EventTypeCustomInput>;
  description: string | null;
  destinationCalendar?: DestinationCalendar | null;
  disableGuests: boolean;
  durationLimits: JsonValue;
  eventName: string | null;
  hashedLink?: HashedLink | null;
  hidden: boolean;
  hideCalendarNotes: boolean;
  hosts?: Array<Host>;
  id: number;
  isInstantEvent: boolean;
  length: number;
  locations: JsonValue;
  lockTimeZoneToggleOnBookingPage: boolean;
  metadata: JsonValue;
  minimumBookingNotice: number;
  offsetStart: number;
  onlyShowFirstAvailableSlot: boolean;
  owner?: User | null;
  parent?: EventType | null;
  periodCountCalendarDays: boolean | null;
  periodDays: number | null;
  periodEndDate: Date | null;
  periodStartDate: Date | null;
  periodType?: "UNLIMITED" | "ROLLING" | "RANGE";
  position: number;
  price: number;
  profile?: Profile | null;
  recurringEvent: JsonValue;
  requiresBookerEmailVerification: boolean;
  requiresConfirmation: boolean;
  schedule?: Schedule | null;
  schedulingType?: "ROUND_ROBIN" | "COLLECTIVE" | "MANAGED" | null;
  seatsPerTimeSlot: number | null;
  seatsShowAttendees: boolean | null;
  seatsShowAvailabilityCount: boolean | null;
  slotInterval: number | null;
  slug: string;
  successRedirectUrl: string | null;
  team?: Team | null;
  timeZone: string | null;
  title: string;
  useEventTypeDestinationCalendarEmail: boolean;
  webhooks?: Array<Webhook>;
  workflows?: Array<WorkflowsOnEventType>;
};
