import { AvailabilityCreateNestedManyWithoutEventTypesInput } from "./AvailabilityCreateNestedManyWithoutEventTypesInput";
import { InputJsonValue } from "../../types";
import { BookingCreateNestedManyWithoutEventTypesInput } from "./BookingCreateNestedManyWithoutEventTypesInput";
import { EventTypeCreateNestedManyWithoutEventTypesInput } from "./EventTypeCreateNestedManyWithoutEventTypesInput";
import { EventTypeCustomInputCreateNestedManyWithoutEventTypesInput } from "./EventTypeCustomInputCreateNestedManyWithoutEventTypesInput";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { HashedLinkWhereUniqueInput } from "../hashedLink/HashedLinkWhereUniqueInput";
import { HostCreateNestedManyWithoutEventTypesInput } from "./HostCreateNestedManyWithoutEventTypesInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { EventTypeWhereUniqueInput } from "./EventTypeWhereUniqueInput";
import { ProfileWhereUniqueInput } from "../profile/ProfileWhereUniqueInput";
import { ScheduleWhereUniqueInput } from "../schedule/ScheduleWhereUniqueInput";
import { TeamWhereUniqueInput } from "../team/TeamWhereUniqueInput";
import { WebhookCreateNestedManyWithoutEventTypesInput } from "./WebhookCreateNestedManyWithoutEventTypesInput";
import { WorkflowsOnEventTypeCreateNestedManyWithoutEventTypesInput } from "./WorkflowsOnEventTypeCreateNestedManyWithoutEventTypesInput";

export type EventTypeCreateInput = {
  afterEventBuffer: number;
  assignAllTeamMembers: boolean;
  availability?: AvailabilityCreateNestedManyWithoutEventTypesInput;
  beforeEventBuffer: number;
  bookingFields?: InputJsonValue;
  bookingLimits?: InputJsonValue;
  bookings?: BookingCreateNestedManyWithoutEventTypesInput;
  children?: EventTypeCreateNestedManyWithoutEventTypesInput;
  currency: string;
  customInputs?: EventTypeCustomInputCreateNestedManyWithoutEventTypesInput;
  description?: string | null;
  destinationCalendar?: DestinationCalendarWhereUniqueInput | null;
  disableGuests: boolean;
  durationLimits?: InputJsonValue;
  eventName?: string | null;
  hashedLink?: HashedLinkWhereUniqueInput | null;
  hidden: boolean;
  hideCalendarNotes: boolean;
  hosts?: HostCreateNestedManyWithoutEventTypesInput;
  isInstantEvent: boolean;
  length: number;
  locations?: InputJsonValue;
  lockTimeZoneToggleOnBookingPage: boolean;
  metadata?: InputJsonValue;
  minimumBookingNotice: number;
  offsetStart: number;
  onlyShowFirstAvailableSlot: boolean;
  owner?: UserWhereUniqueInput | null;
  parent?: EventTypeWhereUniqueInput | null;
  periodCountCalendarDays?: boolean | null;
  periodDays?: number | null;
  periodEndDate?: Date | null;
  periodStartDate?: Date | null;
  periodType: "UNLIMITED" | "ROLLING" | "RANGE";
  position: number;
  price: number;
  profile?: ProfileWhereUniqueInput | null;
  recurringEvent?: InputJsonValue;
  requiresBookerEmailVerification: boolean;
  requiresConfirmation: boolean;
  schedule?: ScheduleWhereUniqueInput | null;
  schedulingType?: "ROUND_ROBIN" | "COLLECTIVE" | "MANAGED" | null;
  seatsPerTimeSlot?: number | null;
  seatsShowAttendees?: boolean | null;
  seatsShowAvailabilityCount?: boolean | null;
  slotInterval?: number | null;
  slug: string;
  successRedirectUrl?: string | null;
  team?: TeamWhereUniqueInput | null;
  timeZone?: string | null;
  title: string;
  useEventTypeDestinationCalendarEmail: boolean;
  webhooks?: WebhookCreateNestedManyWithoutEventTypesInput;
  workflows?: WorkflowsOnEventTypeCreateNestedManyWithoutEventTypesInput;
};
