import { AvailabilityUpdateManyWithoutEventTypesInput } from "./AvailabilityUpdateManyWithoutEventTypesInput";
import { InputJsonValue } from "../../types";
import { BookingUpdateManyWithoutEventTypesInput } from "./BookingUpdateManyWithoutEventTypesInput";
import { EventTypeUpdateManyWithoutEventTypesInput } from "./EventTypeUpdateManyWithoutEventTypesInput";
import { EventTypeCustomInputUpdateManyWithoutEventTypesInput } from "./EventTypeCustomInputUpdateManyWithoutEventTypesInput";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { HashedLinkWhereUniqueInput } from "../hashedLink/HashedLinkWhereUniqueInput";
import { HostUpdateManyWithoutEventTypesInput } from "./HostUpdateManyWithoutEventTypesInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { EventTypeWhereUniqueInput } from "./EventTypeWhereUniqueInput";
import { ProfileWhereUniqueInput } from "../profile/ProfileWhereUniqueInput";
import { ScheduleWhereUniqueInput } from "../schedule/ScheduleWhereUniqueInput";
import { TeamWhereUniqueInput } from "../team/TeamWhereUniqueInput";
import { WebhookUpdateManyWithoutEventTypesInput } from "./WebhookUpdateManyWithoutEventTypesInput";
import { WorkflowsOnEventTypeUpdateManyWithoutEventTypesInput } from "./WorkflowsOnEventTypeUpdateManyWithoutEventTypesInput";

export type EventTypeUpdateInput = {
  afterEventBuffer?: number;
  assignAllTeamMembers?: boolean;
  availability?: AvailabilityUpdateManyWithoutEventTypesInput;
  beforeEventBuffer?: number;
  bookingFields?: InputJsonValue;
  bookingLimits?: InputJsonValue;
  bookings?: BookingUpdateManyWithoutEventTypesInput;
  children?: EventTypeUpdateManyWithoutEventTypesInput;
  currency?: string;
  customInputs?: EventTypeCustomInputUpdateManyWithoutEventTypesInput;
  description?: string | null;
  destinationCalendar?: DestinationCalendarWhereUniqueInput | null;
  disableGuests?: boolean;
  durationLimits?: InputJsonValue;
  eventName?: string | null;
  hashedLink?: HashedLinkWhereUniqueInput | null;
  hidden?: boolean;
  hideCalendarNotes?: boolean;
  hosts?: HostUpdateManyWithoutEventTypesInput;
  isInstantEvent?: boolean;
  length?: number;
  locations?: InputJsonValue;
  lockTimeZoneToggleOnBookingPage?: boolean;
  metadata?: InputJsonValue;
  minimumBookingNotice?: number;
  offsetStart?: number;
  onlyShowFirstAvailableSlot?: boolean;
  owner?: UserWhereUniqueInput | null;
  parent?: EventTypeWhereUniqueInput | null;
  periodCountCalendarDays?: boolean | null;
  periodDays?: number | null;
  periodEndDate?: Date | null;
  periodStartDate?: Date | null;
  periodType?: "UNLIMITED" | "ROLLING" | "RANGE";
  position?: number;
  price?: number;
  profile?: ProfileWhereUniqueInput | null;
  recurringEvent?: InputJsonValue;
  requiresBookerEmailVerification?: boolean;
  requiresConfirmation?: boolean;
  schedule?: ScheduleWhereUniqueInput | null;
  schedulingType?: "ROUND_ROBIN" | "COLLECTIVE" | "MANAGED" | null;
  seatsPerTimeSlot?: number | null;
  seatsShowAttendees?: boolean | null;
  seatsShowAvailabilityCount?: boolean | null;
  slotInterval?: number | null;
  slug?: string;
  successRedirectUrl?: string | null;
  team?: TeamWhereUniqueInput | null;
  timeZone?: string | null;
  title?: string;
  useEventTypeDestinationCalendarEmail?: boolean;
  webhooks?: WebhookUpdateManyWithoutEventTypesInput;
  workflows?: WorkflowsOnEventTypeUpdateManyWithoutEventTypesInput;
};
