/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { SkillWhereUniqueInput } from "../../skill/base/SkillWhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";

@InputType()
class SkillCreateNestedManyWithoutUser1sInput {
  @Field(() => [SkillWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [SkillWhereUniqueInput],
  })
  connect?: Array<SkillWhereUniqueInput>;
}

export { SkillCreateNestedManyWithoutUser1sInput as SkillCreateNestedManyWithoutUser1sInput };
