import { AccessCodeCreateNestedManyWithoutUsersInput } from "./AccessCodeCreateNestedManyWithoutUsersInput";
import { AccountCreateNestedManyWithoutUsersInput } from "./AccountCreateNestedManyWithoutUsersInput";
import { ApiKeyCreateNestedManyWithoutUsersInput } from "./ApiKeyCreateNestedManyWithoutUsersInput";
import { AvailabilityCreateNestedManyWithoutUsersInput } from "./AvailabilityCreateNestedManyWithoutUsersInput";
import { OutOfOfficeEntryCreateNestedManyWithoutUsersInput } from "./OutOfOfficeEntryCreateNestedManyWithoutUsersInput";
import { BookingCreateNestedManyWithoutUsersInput } from "./BookingCreateNestedManyWithoutUsersInput";
import { CredentialCreateNestedManyWithoutUsersInput } from "./CredentialCreateNestedManyWithoutUsersInput";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { FeedbackCreateNestedManyWithoutUsersInput } from "./FeedbackCreateNestedManyWithoutUsersInput";
import { HostCreateNestedManyWithoutUsersInput } from "./HostCreateNestedManyWithoutUsersInput";
import { ImpersonationCreateNestedManyWithoutUsersInput } from "./ImpersonationCreateNestedManyWithoutUsersInput";
import { InputJsonValue } from "../../types";
import { ProfileWhereUniqueInput } from "../profile/ProfileWhereUniqueInput";
import { TeamWhereUniqueInput } from "../team/TeamWhereUniqueInput";
import { EventTypeCreateNestedManyWithoutUsersInput } from "./EventTypeCreateNestedManyWithoutUsersInput";
import { UserPasswordWhereUniqueInput } from "../userPassword/UserPasswordWhereUniqueInput";
import { ProfileCreateNestedManyWithoutUsersInput } from "./ProfileCreateNestedManyWithoutUsersInput";
import { AppRoutingFormsFormCreateNestedManyWithoutUsersInput } from "./AppRoutingFormsFormCreateNestedManyWithoutUsersInput";
import { ScheduleCreateNestedManyWithoutUsersInput } from "./ScheduleCreateNestedManyWithoutUsersInput";
import { SelectedCalendarCreateNestedManyWithoutUsersInput } from "./SelectedCalendarCreateNestedManyWithoutUsersInput";
import { SessionCreateNestedManyWithoutUsersInput } from "./SessionCreateNestedManyWithoutUsersInput";
import { MembershipCreateNestedManyWithoutUsersInput } from "./MembershipCreateNestedManyWithoutUsersInput";
import { VerifiedNumberCreateNestedManyWithoutUsersInput } from "./VerifiedNumberCreateNestedManyWithoutUsersInput";
import { WebhookCreateNestedManyWithoutUsersInput } from "./WebhookCreateNestedManyWithoutUsersInput";
import { WorkflowCreateNestedManyWithoutUsersInput } from "./WorkflowCreateNestedManyWithoutUsersInput";

export type UserCreateInput = {
  accessCodes?: AccessCodeCreateNestedManyWithoutUsersInput;
  accounts?: AccountCreateNestedManyWithoutUsersInput;
  allowDynamicBooking?: boolean | null;
  allowSEOIndexing?: boolean | null;
  apiKeys?: ApiKeyCreateNestedManyWithoutUsersInput;
  appTheme?: string | null;
  availability?: AvailabilityCreateNestedManyWithoutUsersInput;
  avatar?: string | null;
  avatarUrl?: string | null;
  away: boolean;
  backupCodes?: string | null;
  bio?: string | null;
  bookingRedirects?: OutOfOfficeEntryCreateNestedManyWithoutUsersInput;
  bookingRedirectsTo?: OutOfOfficeEntryCreateNestedManyWithoutUsersInput;
  bookings?: BookingCreateNestedManyWithoutUsersInput;
  brandColor?: string | null;
  bufferTime: number;
  completedOnboarding: boolean;
  credentials?: CredentialCreateNestedManyWithoutUsersInput;
  darkBrandColor?: string | null;
  defaultScheduleId?: number | null;
  destinationCalendar?: DestinationCalendarWhereUniqueInput | null;
  disableImpersonation: boolean;
  email: string;
  emailVerified?: Date | null;
  endTime: number;
  feedback?: FeedbackCreateNestedManyWithoutUsersInput;
  hideBranding: boolean;
  hosts?: HostCreateNestedManyWithoutUsersInput;
  identityProvider: "CAL" | "GOOGLE" | "SAML";
  identityProviderId?: string | null;
  impersonatedBy?: ImpersonationCreateNestedManyWithoutUsersInput;
  impersonatedUsers?: ImpersonationCreateNestedManyWithoutUsersInput;
  invitedTo?: number | null;
  locale?: string | null;
  locked: boolean;
  metadata?: InputJsonValue;
  movedToProfile?: ProfileWhereUniqueInput | null;
  name?: string | null;
  organization?: TeamWhereUniqueInput | null;
  ownedEventTypes?: EventTypeCreateNestedManyWithoutUsersInput;
  password?: UserPasswordWhereUniqueInput | null;
  profiles?: ProfileCreateNestedManyWithoutUsersInput;
  receiveMonthlyDigestEmail?: boolean | null;
  role: "USER" | "ADMIN";
  routingForms?: AppRoutingFormsFormCreateNestedManyWithoutUsersInput;
  schedules?: ScheduleCreateNestedManyWithoutUsersInput;
  selectedCalendars?: SelectedCalendarCreateNestedManyWithoutUsersInput;
  sessions?: SessionCreateNestedManyWithoutUsersInput;
  startTime: number;
  teams?: MembershipCreateNestedManyWithoutUsersInput;
  theme?: string | null;
  timeFormat?: number | null;
  timeZone: string;
  trialEndsAt?: Date | null;
  twoFactorEnabled: boolean;
  twoFactorSecret?: string | null;
  username?: string | null;
  verified?: boolean | null;
  verifiedNumbers?: VerifiedNumberCreateNestedManyWithoutUsersInput;
  webhooks?: WebhookCreateNestedManyWithoutUsersInput;
  weekStart: string;
  workflows?: WorkflowCreateNestedManyWithoutUsersInput;
};
