import { AccessCode } from "../accessCode/AccessCode";
import { Account } from "../account/Account";
import { ApiKey } from "../apiKey/ApiKey";
import { Availability } from "../availability/Availability";
import { OutOfOfficeEntry } from "../outOfOfficeEntry/OutOfOfficeEntry";
import { Booking } from "../booking/Booking";
import { Credential } from "../credential/Credential";
import { DestinationCalendar } from "../destinationCalendar/DestinationCalendar";
import { Feedback } from "../feedback/Feedback";
import { Host } from "../host/Host";
import { Impersonation } from "../impersonation/Impersonation";
import { JsonValue } from "type-fest";
import { Profile } from "../profile/Profile";
import { Team } from "../team/Team";
import { EventType } from "../eventType/EventType";
import { UserPassword } from "../userPassword/UserPassword";
import { AppRoutingFormsForm } from "../appRoutingFormsForm/AppRoutingFormsForm";
import { Schedule } from "../schedule/Schedule";
import { SelectedCalendar } from "../selectedCalendar/SelectedCalendar";
import { Session } from "../session/Session";
import { Membership } from "../membership/Membership";
import { VerifiedNumber } from "../verifiedNumber/VerifiedNumber";
import { Webhook } from "../webhook/Webhook";
import { Workflow } from "../workflow/Workflow";

export type User = {
  accessCodes?: Array<AccessCode>;
  accounts?: Array<Account>;
  allowDynamicBooking: boolean | null;
  allowSEOIndexing: boolean | null;
  apiKeys?: Array<ApiKey>;
  appTheme: string | null;
  availability?: Array<Availability>;
  avatar: string | null;
  avatarUrl: string | null;
  away: boolean;
  backupCodes: string | null;
  bio: string | null;
  bookingRedirects?: Array<OutOfOfficeEntry>;
  bookingRedirectsTo?: Array<OutOfOfficeEntry>;
  bookings?: Array<Booking>;
  brandColor: string | null;
  bufferTime: number;
  completedOnboarding: boolean;
  createdDate: Date;
  credentials?: Array<Credential>;
  darkBrandColor: string | null;
  defaultScheduleId: number | null;
  destinationCalendar?: DestinationCalendar | null;
  disableImpersonation: boolean;
  email: string;
  emailVerified: Date | null;
  endTime: number;
  feedback?: Array<Feedback>;
  hideBranding: boolean;
  hosts?: Array<Host>;
  id: number;
  identityProvider?: "CAL" | "GOOGLE" | "SAML";
  identityProviderId: string | null;
  impersonatedBy?: Array<Impersonation>;
  impersonatedUsers?: Array<Impersonation>;
  invitedTo: number | null;
  locale: string | null;
  locked: boolean;
  metadata: JsonValue;
  movedToProfile?: Profile | null;
  name: string | null;
  organization?: Team | null;
  ownedEventTypes?: Array<EventType>;
  password?: UserPassword | null;
  profiles?: Array<Profile>;
  receiveMonthlyDigestEmail: boolean | null;
  role?: "USER" | "ADMIN";
  routingForms?: Array<AppRoutingFormsForm>;
  schedules?: Array<Schedule>;
  selectedCalendars?: Array<SelectedCalendar>;
  sessions?: Array<Session>;
  startTime: number;
  teams?: Array<Membership>;
  theme: string | null;
  timeFormat: number | null;
  timeZone: string;
  trialEndsAt: Date | null;
  twoFactorEnabled: boolean;
  twoFactorSecret: string | null;
  username: string | null;
  verified: boolean | null;
  verifiedNumbers?: Array<VerifiedNumber>;
  webhooks?: Array<Webhook>;
  weekStart: string;
  workflows?: Array<Workflow>;
};
