import { AccessCodeUpdateManyWithoutUsersInput } from "./AccessCodeUpdateManyWithoutUsersInput";
import { AccountUpdateManyWithoutUsersInput } from "./AccountUpdateManyWithoutUsersInput";
import { ApiKeyUpdateManyWithoutUsersInput } from "./ApiKeyUpdateManyWithoutUsersInput";
import { AvailabilityUpdateManyWithoutUsersInput } from "./AvailabilityUpdateManyWithoutUsersInput";
import { OutOfOfficeEntryUpdateManyWithoutUsersInput } from "./OutOfOfficeEntryUpdateManyWithoutUsersInput";
import { BookingUpdateManyWithoutUsersInput } from "./BookingUpdateManyWithoutUsersInput";
import { CredentialUpdateManyWithoutUsersInput } from "./CredentialUpdateManyWithoutUsersInput";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { FeedbackUpdateManyWithoutUsersInput } from "./FeedbackUpdateManyWithoutUsersInput";
import { HostUpdateManyWithoutUsersInput } from "./HostUpdateManyWithoutUsersInput";
import { ImpersonationUpdateManyWithoutUsersInput } from "./ImpersonationUpdateManyWithoutUsersInput";
import { InputJsonValue } from "../../types";
import { ProfileWhereUniqueInput } from "../profile/ProfileWhereUniqueInput";
import { TeamWhereUniqueInput } from "../team/TeamWhereUniqueInput";
import { EventTypeUpdateManyWithoutUsersInput } from "./EventTypeUpdateManyWithoutUsersInput";
import { UserPasswordWhereUniqueInput } from "../userPassword/UserPasswordWhereUniqueInput";
import { ProfileUpdateManyWithoutUsersInput } from "./ProfileUpdateManyWithoutUsersInput";
import { AppRoutingFormsFormUpdateManyWithoutUsersInput } from "./AppRoutingFormsFormUpdateManyWithoutUsersInput";
import { ScheduleUpdateManyWithoutUsersInput } from "./ScheduleUpdateManyWithoutUsersInput";
import { SelectedCalendarUpdateManyWithoutUsersInput } from "./SelectedCalendarUpdateManyWithoutUsersInput";
import { SessionUpdateManyWithoutUsersInput } from "./SessionUpdateManyWithoutUsersInput";
import { MembershipUpdateManyWithoutUsersInput } from "./MembershipUpdateManyWithoutUsersInput";
import { VerifiedNumberUpdateManyWithoutUsersInput } from "./VerifiedNumberUpdateManyWithoutUsersInput";
import { WebhookUpdateManyWithoutUsersInput } from "./WebhookUpdateManyWithoutUsersInput";
import { WorkflowUpdateManyWithoutUsersInput } from "./WorkflowUpdateManyWithoutUsersInput";

export type UserUpdateInput = {
  accessCodes?: AccessCodeUpdateManyWithoutUsersInput;
  accounts?: AccountUpdateManyWithoutUsersInput;
  allowDynamicBooking?: boolean | null;
  allowSEOIndexing?: boolean | null;
  apiKeys?: ApiKeyUpdateManyWithoutUsersInput;
  appTheme?: string | null;
  availability?: AvailabilityUpdateManyWithoutUsersInput;
  avatar?: string | null;
  avatarUrl?: string | null;
  away?: boolean;
  backupCodes?: string | null;
  bio?: string | null;
  bookingRedirects?: OutOfOfficeEntryUpdateManyWithoutUsersInput;
  bookingRedirectsTo?: OutOfOfficeEntryUpdateManyWithoutUsersInput;
  bookings?: BookingUpdateManyWithoutUsersInput;
  brandColor?: string | null;
  bufferTime?: number;
  completedOnboarding?: boolean;
  credentials?: CredentialUpdateManyWithoutUsersInput;
  darkBrandColor?: string | null;
  defaultScheduleId?: number | null;
  destinationCalendar?: DestinationCalendarWhereUniqueInput | null;
  disableImpersonation?: boolean;
  email?: string;
  emailVerified?: Date | null;
  endTime?: number;
  feedback?: FeedbackUpdateManyWithoutUsersInput;
  hideBranding?: boolean;
  hosts?: HostUpdateManyWithoutUsersInput;
  identityProvider?: "CAL" | "GOOGLE" | "SAML";
  identityProviderId?: string | null;
  impersonatedBy?: ImpersonationUpdateManyWithoutUsersInput;
  impersonatedUsers?: ImpersonationUpdateManyWithoutUsersInput;
  invitedTo?: number | null;
  locale?: string | null;
  locked?: boolean;
  metadata?: InputJsonValue;
  movedToProfile?: ProfileWhereUniqueInput | null;
  name?: string | null;
  organization?: TeamWhereUniqueInput | null;
  ownedEventTypes?: EventTypeUpdateManyWithoutUsersInput;
  password?: UserPasswordWhereUniqueInput | null;
  profiles?: ProfileUpdateManyWithoutUsersInput;
  receiveMonthlyDigestEmail?: boolean | null;
  role?: "USER" | "ADMIN";
  routingForms?: AppRoutingFormsFormUpdateManyWithoutUsersInput;
  schedules?: ScheduleUpdateManyWithoutUsersInput;
  selectedCalendars?: SelectedCalendarUpdateManyWithoutUsersInput;
  sessions?: SessionUpdateManyWithoutUsersInput;
  startTime?: number;
  teams?: MembershipUpdateManyWithoutUsersInput;
  theme?: string | null;
  timeFormat?: number | null;
  timeZone?: string;
  trialEndsAt?: Date | null;
  twoFactorEnabled?: boolean;
  twoFactorSecret?: string | null;
  username?: string | null;
  verified?: boolean | null;
  verifiedNumbers?: VerifiedNumberUpdateManyWithoutUsersInput;
  webhooks?: WebhookUpdateManyWithoutUsersInput;
  weekStart?: string;
  workflows?: WorkflowUpdateManyWithoutUsersInput;
};
